### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by liuchunyu524** [Uminosachi/sd-webui-inpaint-anything#107]
Traceback (most recent call last):
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\code\python\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\code\python\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\ia_threading.py", line 159, in yield_wrapper
    yield from func(*args, **kwargs)
  File "C:\code\python\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\ia_threading.py", line 119, in yield_wrapper
    yield from func(*args, **kwargs)
  File "C:\code\python\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 421, in run_inpaint
    for count in range(int(iteration_count)):
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by Uminosachi** [comment]
I discovered that deleting the Iterations counter causes it to become None, leading to an error. I've fixed this issue. Please update and give it a try.

**Comment by Uminosachi** [comment]
The issue with the Iterations variable becoming None has been resolved. This issue is now closed.
