### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by didibus** [Uminosachi/sd-webui-inpaint-anything#110]
When running inpaint-anything with the Inpainting Webui TAB, I get the following error:

```
Traceback (most recent call last):
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/venv/lib64/python3.11/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/user/bin/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/ia_threading.py", line 119, in yield_wrapper
    yield from func(*args, **kwargs)
  File "/home/user/bin/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 794, in run_webui_inpaint
    processed = process_images(p)
                ^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/modules/processing.py", line 732, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/stable-diffusion-webui/modules/processing.py", line 987, in process_images_inner
    info=infotexts[0],
         ~~~~~~~~~^^^
IndexError: list index out of range
```

Here's a screenshot of what I was doing:

![Web capture_17-10-2023_212221_127 0 0 1](https://github.com/Uminosachi/sd-webui-inpaint-anything/assets/601540/19983cc0-25bf-4f6e-9fd2-6114df53f0c4)

**Comment by Uminosachi** [comment]
I've experienced issues when updating extensions like ControlNet in the Extensions tab and trying to run them without restarting the web UI. Please try restarting the web UI from the beginning using `webui.sh`.
