### ISSUE TITLE
ModuleNotFoundError: No module named 'lama_cleaner'

### ISSUE THREAD

**Issue by Hankerlove** [Uminosachi/sd-webui-inpaint-anything#141]
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki\sd-webui-aki-v4.2\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd-webui-aki\sd-webui-aki-v4.2\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd-webui-aki\sd-webui-aki-v4.2\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
    ModuleNotFoundError: No module named 'lama_cleaner'

---

**Comment by Uminosachi** [comment]
I have changed to keep the lama-cleaner package locally. Please update sd-webui-inpaint-anything to the latest version and try it out.

**Comment by Uminosachi** [comment]
I have added the `lama_cleaner` package to this repository, so I am closing this issue.
