### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by kbahaaeldin** [Uminosachi/sd-webui-inpaint-anything#155]
0: 1600x1216 99 objects, 147.1ms
Speed: 9.1ms preprocess, 147.1ms inference, 138.1ms postprocess per image at shape (1, 3, 1600, 1216)
2024-07-30 14:37:22,015 - Inpaint Anything - INFO - sam_masks: 99
Processing segments: 100%|█████████████████████████████████████████████████████████████| 99/99 [00:03<00:00, 32.92it/s]
Traceback (most recent call last):
  File "D:\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\system\python\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\webui\extensions\sd-webui-inpaint-anything\ia_threading.py", line 165, in wrapper
    res = func(*args, **kwargs)
  File "D:\webui\extensions\sd-webui-inpaint-anything\ia_threading.py", line 125, in wrapper
    res = func(*args, **kwargs)
  File "D:\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 207, in run_sam
    if sam_image["image"].shape == seg_image.shape and np.all(sam_image["image"] == seg_image):
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by frankea** [comment]
Same error here.

**Comment by Uminosachi** [comment]
I have tightened the conditions in the if statement when returning images. Please update and try it out.

**Comment by frankea** [comment]
> I have tightened the conditions in the if statement when returning images. Please update and try it out.

It does indeed run successfully now, however after it runs the mouse is just a normal cursor and I can't paint anything to create a mask.

**Comment by Uminosachi** [comment]
The gradio package within the venv might be corrupted. Try deleting the venv folder under stable-diffusion-webui and then restart the webui.bat.

For Windows:
```
rmdir /s venv
webui.bat
```

**Comment by frankea** [comment]
> The gradio package within the venv might be corrupted. Try deleting the venv folder under stable-diffusion-webui and then restart the webui.bat.
> 
> For Windows:
> 
> ```
> rmdir /s venv
> webui.bat
> ```

I did that and got an error regarding PATH, so I ran webui-user.bat which reinstalled everything in the VENV.  After doing so, the issue persists where I only have a normal mouse cursor.  Tried in Firefox and Chrome with the same results.

**Comment by Uminosachi** [comment]
Duplicate of #154

**Comment by Uminosachi** [comment]
This repository currently does not support version 4 of the Gradio package used in stable-diffusion-webui-forge.

**Comment by hanetyb** [comment]
i meet the same issue that its failed to create mask without cursor , will you have a plan to upgrade to support gradio 4?

**Comment by Uminosachi** [comment]
At the moment, I don't have plans to support Gradio 4 due to some existing bugs in the ImageEditor component, particularly issues like image misalignment when used within gradio.Row().

**Comment by jkw117** [comment]
If their are any workarounds I'd appreciate it.

**Comment by Bruce20090827** [comment]
So sd-forge-webui is not supported ?

**Comment by Uminosachi** [comment]
This repository is for [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui.git) and does not support Gradio 4 Forge.
