### ISSUE TITLE
BUG  ModuleNotFoundError: No module named 'hydra'（update SD1.10.0）

### ISSUE THREAD

**Issue by swumagic** [Uminosachi/sd-webui-inpaint-anything#156]
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "J:\StableDiffusion\sdwebui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\StableDiffusion\sdwebui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\StableDiffusion\sdwebui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 32, in <module>
        import inpalib
      File "J:\StableDiffusion\sdwebui\extensions\sd-webui-inpaint-anything\inpalib\__init__.py", line 2, in <module>
        from .samlib import (create_seg_color_image, generate_sam_masks, get_all_sam_ids,
      File "J:\StableDiffusion\sdwebui\extensions\sd-webui-inpaint-anything\inpalib\samlib.py", line 19, in <module>
        from ia_sam_manager import check_bfloat16_support, get_sam_mask_generator  # noqa: E402
      File "J:\StableDiffusion\sdwebui\extensions\sd-webui-inpaint-anything\ia_sam_manager.py", line 16, in <module>
        from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
      File "J:\StableDiffusion\sdwebui\extensions\sd-webui-inpaint-anything\sam2\__init__.py", line 10, in <module>
        from hydra import initialize_config_dir, initialize_config_module  # noqa: F401
    ModuleNotFoundError: No module named 'hydra'

**Comment by swumagic** [comment]
pip install hydra
pip install hydra-core --upgrade
