### ISSUE TITLE
"Inpaint anything" tab vanished

### ISSUE THREAD

**Issue by rtaskf** [Uminosachi/sd-webui-inpaint-anything#157]
A few days ago, the extension suddenly stopped working and the extension's tab isn't there anymore. I upgraded my A1111 installation today. I was still running 1.06. It didn't help, though.

This is from the console on startup:

```
Launching Web UI with arguments: --api --xformers --update-all-extensions --update-check
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "[...]\Git\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "[...]\Git\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "[...]\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 32, in <module>
        import inpalib
      File "[...]\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\inpalib\__init__.py", line 2, in <module>
        from .samlib import (create_seg_color_image, generate_sam_masks, get_all_sam_ids,
      File "[...]\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\inpalib\samlib.py", line 19, in <module>
        from ia_sam_manager import check_bfloat16_support, get_sam_mask_generator  # noqa: E402
      File "[...]\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\ia_sam_manager.py", line 16, in <module>
        from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
      File "[...]\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\sam2\__init__.py", line 17, in <module>
        initialize_config_dir(configs_path, version_base="1.2")
    TypeError: initialize_config_dir.__init__() got an unexpected keyword argument 'version_base'

---
```

Do I need to install the latest python version perhaps? I never had any python-related issues with this or any other extension, so that wouldn't be my first guess. I also haven't chenged my extension setup in many months. It just started a few days ago for no apparent reason.

**Comment by rtaskf** [comment]
It looks like the module "termcolor" is missing. When I try to "pip install" it, I get the next batch of missing requirements. When I try to install those, I get more missing requirements.

I'm really not that good with git, but something seems amiss...

**Comment by rtaskf** [comment]
After fixing the python version mess, I deleted and re-installed both Inpaint Anything and Segment Anything. The error I am getting now is the initial one again, not the missing "termcolor" module anymore. Everything else, A1111 and all other other extensions, are working. I'm officially out of ideas now and would appreciate some help.


```
Launching Web UI with arguments: --api --xformers --update-all-extensions --update-check
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
ControlNet preprocessor location: D:\Programme\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-08-04 14:22:13,727 - ControlNet - INFO - ControlNet v1.1.455
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "D:\Programme\Git\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Programme\Git\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Programme\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 32, in <module>
        import inpalib
      File "D:\Programme\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\inpalib\__init__.py", line 2, in <module>
        from .samlib import (create_seg_color_image, generate_sam_masks, get_all_sam_ids,
      File "D:\Programme\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\inpalib\samlib.py", line 19, in <module>
        from ia_sam_manager import check_bfloat16_support, get_sam_mask_generator  # noqa: E402
      File "D:\Programme\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\ia_sam_manager.py", line 16, in <module>
        from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
      File "D:\Programme\Git\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\sam2\__init__.py", line 17, in <module>
        initialize_config_dir(configs_path, version_base="1.2")
    TypeError: initialize_config_dir.__init__() got an unexpected keyword argument 'version_base'

---
```

**Comment by Uminosachi** [comment]
I have added code to catch the TypeError during SAM 2 initialization. Please update the extension and try again.

**Comment by rtaskf** [comment]
It's finally working again. Thanks.
