### ISSUE TITLE
Could not get source code

### ISSUE THREAD

**Issue by POPORichard** [Uminosachi/sd-webui-inpaint-anything#158]
Hello,
I am using the inpaint-anything plugin of Stable Diffusion WebUI on Stability Matrix. My environment is as follows:

```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]  
Version: v1.10.0
```

I have downloaded Segment Anything Model and other settings are default. When I click Run Segment Anything, the following error message appears:

```
2024-08-06 17:30:53,303 - Inpaint Anything - INFO - input_image: (4204, 2803, 3) uint8
Traceback (most recent call last):
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 191, in run_sam
    sam_masks = inpalib.generate_sam_masks(input_image, sam_model_id, anime_style_chk)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-inpaint-anything\inpalib\samlib.py", line 137, in generate_sam_masks
    sam_mask_generator = get_sam_mask_generator(sam_checkpoint, anime_style_chk)
  File "contextlib.py", line 79, in inner
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-inpaint-anything\ia_sam_manager.py", line 135, in get_sam_mask_generator
    sam_mask_generator = SamAutomaticMaskGeneratorLocal(**sam_gen_kwargs)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-inpaint-anything\sam2\automatic_mask_generator.py", line 120, in __init__
    self.predictor = SAM2ImagePredictor(
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-inpaint-anything\sam2\sam2_image_predictor.py", line 41, in __init__
    self._transforms = SAM2Transforms(
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-inpaint-anything\sam2\utils\transforms.py", line 28, in __init__
    self.transforms = torch.jit.script(
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_script.py", line 1324, in script
    return torch.jit._recursive.create_script_module(
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 556, in create_script_module
    concrete_type = get_module_concrete_type(nn_module, share_types)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 505, in get_module_concrete_type
    concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 438, in get_or_create_concrete_type
    concrete_type_builder = infer_concrete_type_builder(nn_module)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 284, in infer_concrete_type_builder
    sub_concrete_type = get_module_concrete_type(item, share_types)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 505, in get_module_concrete_type
    concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 438, in get_or_create_concrete_type
    concrete_type_builder = infer_concrete_type_builder(nn_module)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 395, in infer_concrete_type_builder
    attr_type, inferred = infer_type(name, value)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_recursive.py", line 234, in infer_type
    attr_type = torch._C._jit_try_infer_type(item)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\annotations.py", line 489, in try_ann_to_type
    scripted_class = torch.jit._script._recursive_compile_class(ann, loc)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\jit\_script.py", line 1506, in _recursive_compile_class
    rcb = _jit_internal.createResolutionCallbackForClassMethods(obj)
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\_jit_internal.py", line 458, in createResolutionCallbackForClassMethods
    captures.update(get_type_hint_captures(fn))
  File "D:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\_jit_internal.py", line 374, in get_type_hint_captures
    src = inspect.getsource(fn)
  File "inspect.py", line 1139, in getsource
  File "inspect.py", line 1121, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code

2024-08-06 17:30:53,845 - Inpaint Anything - ERROR - could not get source code
```

I have tried deleting the `venv` file and installing only this plugin in a new environment, but this error still occurs.

I don't know what I did wrong. Please give me some advice. Thank you very much.

**Comment by Uminosachi** [comment]
I have removed the torch.jit.script that was causing the error. Please update and try again.

**Comment by POPORichard** [comment]
Cheers, problem solved, thanks a lot.
