### ISSUE TITLE
Error Loading script: inpaint_anything.py

### ISSUE THREAD

**Issue by YueWenbo** [Uminosachi/sd-webui-inpaint-anything#164]
```
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
        from diffusers import (DDIMScheduler, EulerAncestralDiscreteScheduler, EulerDiscreteScheduler,
      File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (D:\SD\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\__init__.py)
```

I tired to reinstall, git pull, delete all other extesnsions, detele venv, but it still can't work.

**Comment by Uminosachi** [comment]
The `diffusers` package under `venv` seems to be outdated. Try disabling any other extensions that use `diffusers` and update the `diffusers` package with the following commands:

```
venv\Scripts\activate
pip install --upgrade diffusers
deactivate
```

**Comment by YueWenbo** [comment]
It's working now! Thank you.
