### ISSUE TITLE
Inpaint-Anything Tab missing

### ISSUE THREAD

**Issue by emplifya** [Uminosachi/sd-webui-inpaint-anything#168]
I reinstalled windows on my PC and re-did the same process for installing A1111 and Inpaint Anything as before, but this time i keep getting the same errors.

```
Launching Web UI with arguments:
F:\A1111\stable-diffusion-webui\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\Users\Eugene\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\loaders\ip_adapter.py", line 36, in <module>
        from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, SiglipImageProcessor, SiglipVisionModel
    ImportError: cannot import name 'SiglipImageProcessor' from 'transformers' (F:\A1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\Users\Eugene\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_inpaint.py", line 26, in <module>
        from ...loaders import FromSingleFileMixin, IPAdapterMixin, StableDiffusionLoraLoaderMixin, TextualInversionLoaderMixin
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
    cannot import name 'SiglipImageProcessor' from 'transformers' (F:\A1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "F:\A1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\A1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\A1111\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
        from diffusers import (DDIMScheduler, EulerAncestralDiscreteScheduler, EulerDiscreteScheduler,
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint because of the following error (look up to see its traceback):
    Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
    cannot import name 'SiglipImageProcessor' from 'transformers' (F:\A1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)

```

i have uninstalled, reinstalled everything multiple times; Git, Python, A1111 but still same errors. Help!

**Comment by Uminosachi** [comment]
I have updated the repository. Please update the extension, delete the `venv` folder in the `stable-diffusion-webui` directory, and restart the Web UI using `webui.sh` or `webui.bat`.

**Comment by emplifya** [comment]
it works now! thank you!

**Comment by wmdtk** [comment]
> I have updated the repository. Please update the extension, delete the `venv` folder in the `stable-diffusion-webui` directory, and restart the Web UI using `webui.sh` or `webui.bat`.

*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\AI\Python3.10.6\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\loaders\ip_adapter.py", line 36, in <module>
        from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, SiglipImageProcessor, SiglipVisionModel
    ImportError: cannot import name 'SiglipImageProcessor' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\AI\Python3.10.6\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_inpaint.py", line 26, in <module>
        from ...loaders import FromSingleFileMixin, IPAdapterMixin, StableDiffusionLoraLoaderMixin, TextualInversionLoaderMixin
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
    cannot import name 'SiglipImageProcessor' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
        from diffusers import (DDIMScheduler, EulerAncestralDiscreteScheduler, EulerDiscreteScheduler,
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint because of the following error (look up to see its traceback):
    Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
    cannot import name 'SiglipImageProcessor' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

---
sd-webui-prompt-all-in-one background API service started successfully.
2025-01-01 03:50:14,512 - roop - INFO - roop v0.0.2
2025-01-01 03:50:14,547 - roop - INFO - roop v0.0.2
*** Error loading script: GenParamGetter.py
    Traceback (most recent call last):
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\AI\Python3.10.6\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\loaders\peft.py", line 40, in <module>
        from .lora_base import _fetch_state_dict
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\loaders\lora_base.py", line 47, in <module>
        from peft.tuners.tuners_utils import BaseTunerLayer
      File "C:\AI\Python3.10.6\lib\site-packages\peft\__init__.py", line 22, in <module>
        from .auto import (
      File "C:\AI\Python3.10.6\lib\site-packages\peft\auto.py", line 32, in <module>
        from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
      File "C:\AI\Python3.10.6\lib\site-packages\peft\mapping.py", line 25, in <module>
        from .mixed_model import PeftMixedModel
      File "C:\AI\Python3.10.6\lib\site-packages\peft\mixed_model.py", line 29, in <module>
        from .peft_model import PeftModel
      File "C:\AI\Python3.10.6\lib\site-packages\peft\peft_model.py", line 37, in <module>
        from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
    ImportError: cannot import name 'Cache' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\AI\Python3.10.6\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
        from .autoencoder_asym_kl import AsymmetricAutoencoderKL
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 23, in <module>
        from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\autoencoders\vae.py", line 25, in <module>
        from ..unets.unet_2d_blocks import (
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\unets\__init__.py", line 6, in <module>
        from .unet_2d import UNet2DModel
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in <module>
        from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in <module>
        from ..transformers.dual_transformer_2d import DualTransformer2DModel
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\transformers\__init__.py", line 6, in <module>
        from .cogvideox_transformer_3d import CogVideoXTransformer3DModel
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 22, in <module>
        from ...loaders import PeftAdapterMixin
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
    cannot import name 'Cache' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\GenParamGetter.py", line 5, in <module>
        from scripts.mergers.pluslora import frompromptf
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 21, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 16, in <module>
        from diffusers import AutoencoderKL, DDIMScheduler, StableDiffusionPipeline  # , UNet2DConditionModel
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
    Failed to import diffusers.loaders.peft because of the following error (look up to see its traceback):
    cannot import name 'Cache' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

---
*** Error loading script: supermerger.py
    Traceback (most recent call last):
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\AI\Python3.10.6\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\loaders\ip_adapter.py", line 36, in <module>
        from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, SiglipImageProcessor, SiglipVisionModel
    ImportError: cannot import name 'SiglipImageProcessor' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\AI\Python3.10.6\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 24, in <module>
        from ...loaders import FromSingleFileMixin, IPAdapterMixin, StableDiffusionLoraLoaderMixin, TextualInversionLoaderMixin
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
    cannot import name 'SiglipImageProcessor' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\supermerger.py", line 25, in <module>
        import scripts.mergers.pluslora
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 21, in <module>
        from scripts.kohyas import extract_lora_from_models as ext
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\extract_lora_from_models.py", line 12, in <module>
        from scripts.kohyas import sai_model_spec,model_util,sdxl_model_util,lora
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\kohyas\model_util.py", line 16, in <module>
        from diffusers import AutoencoderKL, DDIMScheduler, StableDiffusionPipeline  # , UNet2DConditionModel
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
        value = getattr(module, name)
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "C:\AI\Python3.10.6\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
    Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
    cannot import name 'SiglipImageProcessor' from 'transformers' (C:\AI\Python3.10.6\lib\site-packages\transformers\__init__.py)

I did this, but it didn't work.

**Comment by Uminosachi** [comment]
In the Web UI's Extensions tab, try clicking `Check for updates` and then clicking `Apply and restart UI`.

**Comment by wmdtk** [comment]
> In the Web UI's Extensions tab, try clicking `Check for updates` and then clicking `Apply and restart UI`.

It's a problem with my environment. Thank you very much.

**Comment by avachon100510** [comment]
I found out that SigLIP was added in transformers 4.37.0, so an easy fix would be to set transformers>=4.37.0 in the required modules list in the install.py file.

**Comment by xieyi1111111** [comment]
> 我在我的电脑上重新安装了 Windows，并重新执行了与之前安装 A1111 和 Inpaint Anything 相同的过程，但这次我仍然收到相同的错误。
> 
> ```
> Launching Web UI with arguments:
> F:\A1111\stable-diffusion-webui\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
>   warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
> no module 'xformers'. Processing without...
> no module 'xformers'. Processing without...
> No module 'xformers'. Proceeding without it.
> *** Error loading script: inpaint_anything.py
>     Traceback (most recent call last):
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
>         return importlib.import_module("." + module_name, self.__name__)
>       File "C:\Users\Eugene\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
>         return _bootstrap._gcd_import(name[level:], package, level)
>       File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>       File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>       File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>       File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\loaders\ip_adapter.py", line 36, in <module>
>         from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, SiglipImageProcessor, SiglipVisionModel
>     ImportError: cannot import name 'SiglipImageProcessor' from 'transformers' (F:\A1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)
> 
>     The above exception was the direct cause of the following exception:
> 
>     Traceback (most recent call last):
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
>         return importlib.import_module("." + module_name, self.__name__)
>       File "C:\Users\Eugene\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
>         return _bootstrap._gcd_import(name[level:], package, level)
>       File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>       File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>       File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>       File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_inpaint.py", line 26, in <module>
>         from ...loaders import FromSingleFileMixin, IPAdapterMixin, StableDiffusionLoraLoaderMixin, TextualInversionLoaderMixin
>       File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
>         module = self._get_module(self._class_to_module[name])
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
>         raise RuntimeError(
>     RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
>     cannot import name 'SiglipImageProcessor' from 'transformers' (F:\A1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)
> 
>     The above exception was the direct cause of the following exception:
> 
>     Traceback (most recent call last):
>       File "F:\A1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "F:\A1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "F:\A1111\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
>         from diffusers import (DDIMScheduler, EulerAncestralDiscreteScheduler, EulerDiscreteScheduler,
>       File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
>         value = getattr(module, name)
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
>         value = getattr(module, name)
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
>         module = self._get_module(self._class_to_module[name])
>       File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
>         raise RuntimeError(
>     RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint because of the following error (look up to see its traceback):
>     Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
>     cannot import name 'SiglipImageProcessor' from 'transformers' (F:\A1111\stable-diffusion-webui\venv\lib\site-packages\transformers\__init__.py)
> ```
> 
> 我已经卸载并重新安装了所有东西多次；Git、Python、A1111，但仍然出现同样的错误。救命！
脚本中指定的版本限制（diffusers<0.32.0），降至0.31.0即可

**Comment by Uminosachi** [comment]
Please try the following commands in the `stable-diffusion-webui` folder.

For Windows:
```
.\venv\Scripts\activate
pip install 'diffusers<0.32.0'
deactivate
```
