### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by patdelphi** [Uminosachi/sd-webui-inpaint-anything#24]
I'm using a webui repackage app, after install sb-webui-inpaint-anything extension, restart the webui and then get the error msg below:

Error loading script: main.py
Traceback (most recent call last):
  File "C:\novelai-webui-aki-v2\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\novelai-webui-aki-v2\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\novelai-webui-aki-v2\extensions\sd-webui-inpaint-anything\scripts\main.py", line 6, in <module>
    from diffusers import StableDiffusionInpaintPipeline, DDIMScheduler, UniPCMultistepScheduler
ImportError: cannot import name 'UniPCMultistepScheduler' from 'diffusers' (C:\novelai-webui-aki-v2\py310\lib\site-packages\diffusers\__init__.py)

Seems it's the name conflict with 'diffusers', can't solve by myself, pls check and help, thx~

**Comment by patdelphi** [comment]
Seems in the package I used, 'diffusers' doesn't have the UniPCMultistepScheduler. I may need to find the right version of 'diffusers'.

**Comment by Uminosachi** [comment]
I have now removed the UniPCMultistepScheduler import as it was not being utilized in the program.

**Comment by patdelphi** [comment]
Greatly appreciate such prompt feedback!

Reinstall the whole package, problem solved~ Thx again and best wishes!
