### ISSUE TITLE
[Bug] - Extension does not work without XFormers installed - (Instructions suggest it should be optional)

### ISSUE THREAD

**Issue by CCpt5** [Uminosachi/sd-webui-inpaint-anything#26]
The instructions on the main page seem to indicate the XFormers is optional,, however the extension errors on generating if XFormers is not installed. Many users who have upgraded to pytorch 2.0+ no longer use XFormers and instead use SDP (which is part of pytorch 2.0+).

If the extension does require XFormers please just clarify that. At the moment the error below appears when trying to run on the current commit of A1111 w/o XFormers installed and nothing is generated. I have used the extension w/o issues on a different venv/install on a different drive that does have XFormers installed. 

Error w/o XFormers: 

____
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Version: v1.3.0
Commit hash: 20ae71faa8ef035c31aa3a410b707d792c8203a3
Installing requirements

Installing frame2frame requirement: opencv-python

Launching Web UI with arguments: --opt-sdp-attention --no-half-vae --opt-channelslast --skip-torch-cuda-test --skip-version-check --ckpt-dir e:\Stable Diffusion Checkpoints
No module 'xformers'. Proceeding without it.
ControlNet v1.1.202
ControlNet v1.1.202
Loading weights [6ce0161689] from E:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Creating model from config: E:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 6.6s (import torch: 1.2s, import gradio: 0.8s, import ldm: 0.4s, other imports: 0.6s, list SD models: 0.1s, load scripts: 2.4s, create ui: 0.5s, gradio launch: 0.6s).
Loading VAE weights specified in settings: E:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying optimization: sdp... done.
Textual inversion embeddings loaded(0):
Model loaded in 3.1s (load weights from disk: 0.3s, create model: 1.1s, apply weights to model: 0.5s, apply channels_last: 0.2s, apply half(): 0.3s, load VAE: 0.4s, move model to device: 0.4s).
input_image: (1039, 1920, 3) uint8
SamAutomaticMaskGenerator sam_vit_l_0b3195.pth
runwayml/stable-diffusion-inpainting
vae\diffusion_pytorch_model.safetensors not found
Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████| 16/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\main.py", line 365, in run_inpaint
    pipe.enable_xformers_memory_efficient_attention()
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1080, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1096, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 219, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 212, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 219, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 212, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\cross_attention.py", line 125, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers

**Comment by Uminosachi** [comment]
Thank you for your suggestion. Fixed the issue of pipeline setting when xformers are disabled. Please verify if the issue has been resolved.
