### ISSUE TITLE
Error loading 

### ISSUE THREAD

**Issue by lundejd** [Uminosachi/sd-webui-inpaint-anything#30]
Getting errors for this one. First time I've ever had errors with an extension. Disabling it makes the error go away of course.

Error loading script: main.py
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/main.py", line 6, in <module>
    from diffusers import StableDiffusionInpaintPipeline, DDIMScheduler
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/diffusers/__init__.py", line 55, in <module>
    from .pipelines import (
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/__init__.py", line 46, in <module>
    from .paint_by_example import PaintByExamplePipeline
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/paint_by_example/__init__.py", line 13, in <module>
    from .pipeline_paint_by_example import PaintByExamplePipeline
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/paint_by_example/pipeline_paint_by_example.py", line 29, in <module>
    from ..stable_diffusion import StableDiffusionPipelineOutput
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/__init__.py", line 81, in <module>
    from .pipeline_stable_diffusion_pix2pix_zero import StableDiffusionPix2PixZeroPipeline
  File "/home/ubuntu/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_pix2pix_zero.py", line 23, in <module>
    from transformers import (
ImportError: cannot import name 'BlipForConditionalGeneration' from 'transformers' (/home/ubuntu/miniconda3/lib/python3.10/site-packages/transformers/__init__.py)

**Comment by lundejd** [comment]
Ok for those that may have run into this, be sure you update to the latest 1.3 before installing this. Once I upgraded all works fine.
