### ISSUE TITLE
Cant run it offline, can we run it offline in automatic1111?

### ISSUE THREAD

**Issue by ManishSthaa** [Uminosachi/sd-webui-inpaint-anything#41]
While clicking Run Inpainting without internet connection, it does not work because it tries to connect to huggingface even when the necessary files have already been downloaded.

Can this be fixed? I noticed this as I have been using mobile connecting tethered to my desktop and using my phone to connect to automatic1111.

Logs:

Traceback (most recent call last):
  File "C:\Users\ADMIN\sstable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020C95EBCF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\ADMIN\table-diffusion-webui\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-2-inpainting (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020C95EBCF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\ADMINstable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\ADMIN\seait.v0.1.2\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\ADMIN\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\main.py", line 357, in run_inpaint
    pipe = StableDiffusionInpaintPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 604, in from_pretrained
    info = model_info(
  File "C:\Users\ADMIN\\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hf_api.py", line 1603, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ADMIN\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-2-inpainting (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020C95EBCF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by Uminosachi** [comment]
In v1.5.2, I added a checkbox labeled `Enable offline network Inpainting` in the `Inpaint Anything` section of the Web UI Settings. When this option is selected, the program will print a message and return if there are no model files available locally.

**Comment by ManishSthaa** [comment]
confirmed its working, wow thanks for quick fix

**Comment by Uminosachi** [comment]
The diffusers' inpainting model can be run without network access if it's stored locally. Therefore, this issue will be closed.
