### ISSUE TITLE
add a resize image option

### ISSUE THREAD

**Issue by efraxs** [Uminosachi/sd-webui-inpaint-anything#51]
Im getting next error and im guessing is cause the size of the image, with a resize image option this should be solved.

>  Model loaded in 4.5s (create model: 0.3s, apply weights to model: 2.7s, apply half(): 0.6s, move model to device: 0.9s).Unloaded weights 0.0s.
> 
> saik0s/realistic_vision_inpainting
> Using sampler DPM2 a Karras
> resize: (3088, 2316) -> (3088, 2316)
> center_crop: (3088, 2316) -> (3088, 2312)
>  25%|████████████████████▊                                                              | 5/20 [01:07<03:16, 13.07s/it]Loading weights [61dcb253a3] from C:\stable-diffusion-webui\models\Stable-diffusion\urpmv12Inpainting-inpainting.safetensors
> Creating model from config: C:\stable-diffusion-webui\configs\v1-inpainting-inference.yaml
> LatentInpaintDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.54 M params.
>  95%|█████████████████████████████████████████████████████████████████████████████▉    | 19/20 [04:03<00:12, 12.27s/it]Applying optimization: xformers... done.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [04:09<00:00, 12.47s/it]
> Model loaded in 183.7s (create model: 0.6s, apply weights to model: 5.7s, apply half(): 1.1s, load VAE: 2.3s, move model to device: 161.4s, load textual inversion embeddings: 12.4s).
> Traceback (most recent call last):
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
>     output = await app.get_blocks().process_api(
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
>     result = await self.call_function(
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "C:\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 549, in run_inpaint
>     output_image = pipe(**pipe_args_dict).images[0]
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_inpaint.py", line 898, in __call__
>     image = self.decode_latents(latents)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_inpaint.py", line 528, in decode_latents
>     image = self.vae.decode(latents).sample
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
>     return method(self, *args, **kwargs)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\autoencoder_kl.py", line 191, in decode
>     decoded = self._decode(z).sample
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\autoencoder_kl.py", line 178, in _decode
>     dec = self.decoder(z)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 238, in forward
>     sample = up_block(sample)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1994, in forward
>     hidden_states = upsampler(hidden_states)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 157, in forward
>     hidden_states = self.conv(hidden_states)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 415, in lora_Conv2d_forward
>     return torch.nn.Conv2d_forward_before_lora(self, input)
>   File "C:\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 753, in lyco_Conv2d_forward
>     return torch.nn.Conv2d_forward_before_lyco(self, input)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
>     return F.conv2d(input, weight, bias, self.stride,
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.41 GiB (GPU 0; 11.99 GiB total capacity; 10.00 GiB already allocated; 0 bytes free; 11.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Uminosachi** [comment]
I don't believe it's a high priority since images can be resized in advance using other apps, but I'll consider its necessity.
