### ISSUE TITLE
Error loading script: inpaint_anything

### ISSUE THREAD

**Issue by lhkjacky** [Uminosachi/sd-webui-inpaint-anything#56]
The extension is working yesterday without any problem.
But today I start the WebUI and it get error from inpaint anything.
The WebUI start but the inpaint anything tab is missing.

Here is the error : 
```
Error loading script: inpaint_anything.py
Traceback (most recent call last):
  File "C:\Users\XXXXXXX\Downloads\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\XXXXXXX\Downloads\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XXXXXXX\Downloads\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 20, in <module>
    from lama_cleaner.model_manager import ModelManager
  File "C:\Users\XXXXXXX\Downloads\stable-diffusion-webui\venv\lib\site-packages\lama_cleaner\model_manager.py", line 8, in <module>
    from lama_cleaner.model.controlnet import ControlNet
  File "C:\Users\XXXXXXX\Downloads\stable-diffusion-webui\venv\lib\site-packages\lama_cleaner\model\controlnet.py", line 7, in <module>
    from diffusers import ControlNetModel
ImportError: cannot import name 'ControlNetModel' from 'diffusers' (C:\Users\XXXXXXX\Downloads\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)
```
I remember I have updated extension last night.
It seem that the update of controlnet or inpaint anything, break the installation.

Thanks all for help

PS: I have tried delete the inpaint anything extension folder and reinstall it again but it does not fix the problem

**Comment by Uminosachi** [comment]
It's possible that your package is corrupted. I recommend deleting the `venv` folder in the `stable-diffusion-webui` folder, then run 'webui.bat' to reinstall the package from scratch.

**Comment by lhkjacky** [comment]
It seem that it happen everytime, when I enable "sd-webui-train-tools" extension.
Once I enable "sd-webui-train-tools" extension, it automatically start installing requirements. After that, error from inpaint-anything.

The only ways to fix it is to, disable the  "sd-webui-train-tools" extension, delete the "inpaint anything" extension folder and venv folder.
Then run webui.bat and reinstall  "inpaint anything" extension

**Comment by Uminosachi** [comment]
The error is occurring because the version specified for diffusers[torch]==0.10.2 in the requirements.txt file of sd-webui-train-tools is quite outdated.
