### ISSUE TITLE
 Error loading script: inpaint_anything.py   ImportError: cannot import name 'await_pre_unload_model_weights' from 'ia_threading' 

### ISSUE THREAD

**Issue by swumagic** [Uminosachi/sd-webui-inpaint-anything#73]
*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 43, in <module>
        from ia_threading import (clear_cache_decorator, await_pre_unload_model_weights, await_pre_reload_model_weights, await_backup_reload_ckpt_info,
    ImportError: cannot import name 'await_pre_unload_model_weights' from 'ia_threading' (M:\SD\sdwebui\extensions\Mask2Background\ia_threading.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by swumagic** [comment]
2 plugin conflicts 
https://github.com/Uminosachi/sd-webui-inpaint-anything
https://github.com/limithit/Mask2Background

**Comment by Uminosachi** [comment]
The Mask2Background repository appears to have been created by duplicating the contents of this Inpaint Anything repository, resulting in overlapping python file names.

**Comment by Uminosachi** [comment]
The issue have been resolved in the Mask2Background repository. Therefore, I am going to close this issue now.
