### ISSUE TITLE
Error loading script: inpaint_anything.py

### ISSUE THREAD

**Issue by lucifer726** [Uminosachi/sd-webui-inpaint-anything#75]
Error loading script: inpaint_anything.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/root/autodl-tmp/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-inpaint-anything-main/scripts/inpaint_anything.py", line 46, in <module>
    from ia_threading import (clear_cache_decorator, await_pre_unload_model_weights, await_pre_reload_model_weights, await_backup_reload_ckpt_info,
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-inpaint-anything-main/ia_threading.py", line 4, in <module>
    from modules.sd_models import unload_model_weights, reload_model_weights
ImportError: cannot import name 'unload_model_weights' from 'modules.sd_models' (/root/autodl-tmp/stable-diffusion-webui/modules/sd_models.py)

**Comment by Uminosachi** [comment]
Duplicate of #62

**Comment by Uminosachi** [comment]
The version of [webUI](https://github.com/AUTOMATIC1111/stable-diffusion-webui) you are currently using might be outdated. To update it, you can execute the `git pull` command in your local `stable-diffusion-webui` directory. 

Alternatively, you can download specific versions directly from the 'tags' page on GitHub.

[https://github.com/AUTOMATIC1111/stable-diffusion-webui/tags](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tags)
